config/routes.rb
Rails.application.routes.draw do
    
    root 'pages#index'
    
  get 'pages/index'

  get 'pages/contact'

  get 'pages/gallery'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def gallery
      @images = [['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle'],
          ['https://unsplash.it/200','subtitle']
          ]

          @items = ["car", "truck", "tank"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalCollection</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/gallery.html.erb
<h1 class="header">GALLERY</h1>


<div class="container">
        <% @images.each do |array|%>
    <div class="box">
       <img src ='<%=array[0]%>'>
       <p><%=array[1]%></p>
    </div>
        <% end %>
</div>

<% @items.each do |x| %>
<%= x %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to 'This goes to the contact page', pages_contact_path %>
<a href="/pages/gallery">Gallery</a>